# Generated by Django 3.1 on 2023-07-18 17:56

import car.apps.users.files
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_environmentalauthorities_government'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=car.apps.users.files.user_avatar_image_path, verbose_name='Foto de Perfil'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='base.city', verbose_name='Ciudad/municipio'),
        ),
        migrations.AddField(
            model_name='user',
            name='enviromental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.environmentalauthorities', verbose_name='Autoridad Ambiental'),
        ),
        migrations.AddField(
            model_name='user',
            name='government',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.government', verbose_name='Gobernación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_user',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Administrador'), (1, 'Gestor de contenido'), (2, 'Usuario por municipio')], default=2, help_text='Administración / Cliente', verbose_name='Tipo de Usuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Numero de cedula / email', max_length=340, unique=True, verbose_name='Username'),
        ),
    ]
