version: "3.7"

services:
  postgres:
    image: postgres
    container_name: postgres_car
    ports:
      - "5432:5432"
    volumes:
      - .data/:/tmp
    environment:
      POSTGRES_DB: car_db
      POSTGRES_USER: car_user
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: car_password
      PGDATA: /tmp

  redis:
    image: bitnami/redis:latest
    container_name: redis_car
    ports:
      - "6379:6379"
    environment:
      ALLOW_EMPTY_PASSWORD: "no"
      REDIS_PASSWORD: ABCDE

  car:
    build: .
    env_file:
      - .env
    volumes:
      - .:/backend
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
