# Generated by Django 3.1 on 2023-07-18 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_environmentalauthorities_government'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='government',
            field=models.ManyToManyField(blank=True, related_name='city_government', to='base.Government', verbose_name='Gobernación'),
        ),
        migrations.AddField(
            model_name='government',
            name='environmental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.environmentalauthorities', verbose_name='Autoridad Ambiental'),
        ),
    ]
